### ISSUE TITLE
Реализовать работу репозитория через итерактор

### ISSUE THREAD

**Issue by dienyaaa** [Yekaterinburg-Tree-Map/ekbtrees-android#3]
- Viewmodel работает с итерактором
- Итерактор вызывает репозиторий
- Репозиторий представляется итерактору через конструктор

**Comment by IlyaDeryabin** [comment]
Данная задача была решена в этом [pull request](https://github.com/Yekaterinburg-Tree-Map/ekbtrees-android/pull/1).
